[server]
headless = true
port = 8501
enableCORS = false

[runner]
magicEnabled = true

[theme]
primaryColor = "#1E88E5"
backgroundColor = "#F9FAFB"
secondaryBackgroundColor = "#E3F2FD"
textColor = "#0D47A1"
